# Generated by Django 4.1.1 on 2022-09-10 21:27

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('meat_category', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('edo', 'Edo'), ('ekiti', 'Ekiti'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo')], default='lagos', max_length=200)),
                ('country', django_countries.fields.CountryField(default='NG', max_length=2)),
                ('total_meat', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('description', models.TextField()),
                ('store_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['store_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_customer', models.BooleanField(default=False)),
                ('is_store', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(default='', max_length=32)),
                ('stipend', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=11)),
                ('state', models.CharField(choices=[('edo', 'Edo'), ('ekiti', 'Ekiti'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo')], default='lagos', max_length=200)),
                ('country', django_countries.fields.CountryField(default='NG', max_length=2)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainContainer.store')),
            ],
        ),
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.TextField()),
                ('meat_size', models.CharField(max_length=200)),
                ('meat_price', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('slaughtered_date', models.DateTimeField(auto_now_add=True)),
                ('meat_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meat_categories', to='MainContainer.store', verbose_name='Meat Category')),
                ('meat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainContainer.meattype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
